nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']
        allow_methods: ['*']
        allow_headers: ['Content-Type', 'Authorization', 'Accept', 'Accept-Language', 'Cache-Control', 'User-Agent', 'Referer']
        expose_headers: ['*']
        max_age: 3600
    paths:
        '^/api':
            allow_origin: ['*']
            allow_headers: ['Content-Type', 'Authorization', 'Accept', 'Accept-Language', 'Cache-Control', 'User-Agent', 'Referer']
            allow_methods: ['*']
